### ISSUE TITLE
raspberrypi

### ISSUE THREAD

**Issue by submax82** [oddjobz/pymamba#1]
I try on my raspberry but i had an error:

> python -c "import lmdb; from pymamba import Database;  print(lmdb.version()); Database('test.mdb')"
> (0, 9, 18)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/opt/python2.7/lib/python2.7/site-packages/pymamba/__init__.py", line 73, in __init__
>     self._env = Environment(name, **conf)
> lmdb.InvalidParameterError: test.mdb: Invalid argument
> Exception AttributeError: "'Database' object has no attribute '_env'" in <bound method Database.__del__ of <pymamba.Database object at 0x76a54d10>> ignored

**Comment by oddjobz** [comment]
Hi, 

Sorry, I think you might need Python3 ... also (!) you might want to check the Pi's storage supports "sparse" storage .. if not, you probably shouldn't be trying this .. :( 

Gareth Bult 
Mad Penguin Consulting Ltd 
Phone : 07853 305393 , Skype : gareth_bult 
Mad Penguin Consulting is a limited company registered in England and Wales (10744763) 
Statements made are subject to Terms and Conditions of Business which are available upon request.

**Comment by submax82** [comment]
On my pc, with python 2.7.12 it's run...

**Comment by oddjobz** [comment]
Interesting .. I'm afraid I've not tried it on a Pi ... 

Gareth Bult 
Mad Penguin Consulting Ltd 
Phone : 07853 305393 , Skype : gareth_bult 
Mad Penguin Consulting is a limited company registered in England and Wales (10744763) 
Statements made are subject to Terms and Conditions of Business which are available upon request.

**Comment by submax82** [comment]
problem is:

> map_size:
> Maximum size database may grow to; used to size the memory mapping. If database grows larger than map_size, an exception will be raised and the user must close and reopen Environment. On 64-bit there is no penalty for making this huge (say 1TB). Must be <2GB on 32-bit.

You set 2147483648 = 2GB

**Comment by oddjobz** [comment]
Ahh, makes sense ... :) 

Gareth Bult 
Mad Penguin Consulting Ltd 
Phone : 07853 305393 , Skype : gareth_bult 
Mad Penguin Consulting is a limited company registered in England and Wales (10744763) 
Statements made are subject to Terms and Conditions of Business which are available upon request.
